# .readthedocs.yml
version: 2

# Specify the build environment
build:
  os: "ubuntu-20.04"  # You can change this to "ubuntu-22.04" if you prefer

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt
    - requirements: requirements-optional.txt
